modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="dragonsurge"
version="1.0.0"
displayName="DragonSurge1.0_1"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nick, MCreator"

[[dependencies.dragonsurge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



